/**
 * Spec database: a compact projection of the official X3D Unified Object Model
 * (X3DUOM 4.0) generated by scripts/build-uom.mjs.
 *
 * Everything the linter, the editor autocompletion and the AI's `lookup_node`
 * tool know about X3D nodes and fields comes from here - i.e. from the
 * ISO/IEC 19775-1 specification itself, not from model memory.
 */
import raw from "../generated/x3duom.json";

export interface FieldDef {
  /** X3D field type, e.g. SFVec3f, MFNode */
  t: string;
  /** accessType: initializeOnly | inputOnly | outputOnly | inputOutput */
  a: string;
  /** default value as written in the spec */
  d?: string;
  /** acceptableNodeTypes for SFNode/MFNode fields */
  n?: string[];
  /** inheritedFrom (abstract type) */
  i?: string;
  /** required attribute (statements) */
  r?: boolean;
  min?: string;
  max?: string;
  desc?: string;
  enum?: string;
}

export interface TypeDef {
  component?: string;
  level?: number;
  base?: string;
  implements?: string[];
  url?: string;
  info?: string;
  containerField?: string;
  containerFields?: string[];
  fields: Record<string, FieldDef>;
}

export interface UomDb {
  version: string;
  source: string;
  fieldTypes: string[];
  enums: Record<string, string[]>;
  abstract: Record<string, TypeDef>;
  nodes: Record<string, TypeDef>;
  statements: Record<string, TypeDef>;
}

export const uom = raw as unknown as UomDb;

export const nodeNames: string[] = Object.keys(uom.nodes).sort();
export const statementNames: string[] = Object.keys(uom.statements).sort();

/** Attributes that every node accepts even though some UOM entries omit them. */
export const UNIVERSAL_ATTRS = new Set(["DEF", "USE", "containerField", "class", "id", "style"]);

export function getNode(name: string): TypeDef | undefined {
  return uom.nodes[name];
}

export function getStatement(name: string): TypeDef | undefined {
  return uom.statements[name];
}

export function getType(name: string): TypeDef | undefined {
  return uom.nodes[name] ?? uom.abstract[name];
}

/** All ancestor type names (abstract node types + implemented object types) of a node or abstract type. */
export function ancestorsOf(typeName: string): Set<string> {
  const seen = new Set<string>();
  const stack = [typeName];
  while (stack.length) {
    const cur = stack.pop()!;
    if (seen.has(cur)) continue;
    seen.add(cur);
    const def = getType(cur);
    if (!def) continue;
    if (def.base) stack.push(def.base);
    for (const impl of def.implements ?? []) stack.push(impl);
  }
  return seen;
}

/** True if concrete/abstract type `typeName` is, or derives from, `wanted`. */
export function isA(typeName: string, wanted: string): boolean {
  if (typeName === wanted) return true;
  return ancestorsOf(typeName).has(wanted);
}

/** True if a node of type `typeName` is acceptable for a field whose acceptableNodeTypes is `accepts`. */
export function acceptsNode(accepts: string[] | undefined, typeName: string): boolean {
  if (!accepts || accepts.length === 0) return true;
  // ProtoInstance can stand in for anything; X3DNode accepts all nodes.
  if (typeName === "ProtoInstance") return true;
  return accepts.some((a) => a === "X3DNode" || isA(typeName, a));
}

/** Concrete node types deriving from an abstract type, e.g. all X3DGeometryNode. */
export function concreteNodesOf(abstractType: string): string[] {
  return nodeNames.filter((n) => isA(n, abstractType));
}

/**
 * Resolve a field name used in a ROUTE to its spec name. For inputOutput
 * fields the spec allows the aliases set_<name> and <name>_changed; anything
 * else must match exactly (X_ITE rejects e.g. 'fraction' for 'fraction_changed').
 */
export function canonicalFieldName(def: TypeDef, field: string): string | undefined {
  if (def.fields[field]) return field;
  if (field.startsWith("set_")) {
    const base = field.slice(4);
    if (def.fields[base]?.a === "inputOutput") return base;
  }
  if (field.endsWith("_changed")) {
    const base = field.slice(0, -8);
    if (def.fields[base]?.a === "inputOutput") return base;
  }
  return undefined;
}

export function canReceiveEvents(access: string): boolean {
  return access === "inputOnly" || access === "inputOutput";
}

export function canSendEvents(access: string): boolean {
  return access === "outputOnly" || access === "inputOutput";
}

/** Damerau-free Levenshtein distance for "did you mean" suggestions. */
export function editDistance(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  const dp: number[] = Array.from({ length: n + 1 }, (_, j) => j);
  for (let i = 1; i <= m; i++) {
    let prev = dp[0];
    dp[0] = i;
    for (let j = 1; j <= n; j++) {
      const tmp = dp[j];
      dp[j] = Math.min(dp[j] + 1, dp[j - 1] + 1, prev + (a[i - 1] === b[j - 1] ? 0 : 1));
      prev = tmp;
    }
  }
  return dp[n];
}

export function suggest(name: string, candidates: Iterable<string>, maxDistance = 3): string | undefined {
  let best: string | undefined;
  let bestD = Infinity;
  let prefixMatch: string | undefined;
  const lower = name.toLowerCase();
  for (const c of candidates) {
    const lc = c.toLowerCase();
    if (lc === lower) return c;
    const d = editDistance(lower, lc);
    if (d < bestD) {
      bestD = d;
      best = c;
    }
    // e.g. 'fraction' -> 'fraction_changed', 'bind' -> 'set_bind'
    if (lower.length >= 4 && (lc.startsWith(lower) || lc.endsWith(lower)) && (!prefixMatch || c.length < prefixMatch.length)) prefixMatch = c;
  }
  return bestD <= maxDistance ? best : prefixMatch;
}

/** Human-readable spec summary of a node, used by the AI `lookup_node` tool. */
export function describeNode(name: string, opts: { includeInherited?: boolean } = {}): string | undefined {
  const def = getNode(name) ?? getStatement(name) ?? uom.abstract[name];
  if (!def) return undefined;
  const lines: string[] = [];
  lines.push(`${name}${def.base ? ` : ${def.base}` : ""}${def.component ? `  [component ${def.component} level ${def.level}]` : ""}`);
  if (def.info) lines.push(def.info);
  if (def.containerField) {
    lines.push(`Default containerField: ${def.containerField}${def.containerFields && def.containerFields.length > 1 ? ` (allowed: ${def.containerFields.join(", ")})` : ""}`);
  }
  if (def.url) lines.push(`Spec: ${def.url}`);
  lines.push("Fields:");
  for (const [fname, f] of Object.entries(def.fields)) {
    if (UNIVERSAL_ATTRS.has(fname) || fname === "IS") continue;
    if (!opts.includeInherited && f.i && (fname === "metadata")) continue;
    let s = `  ${fname}: ${f.t} ${f.a}`;
    if (f.d !== undefined) s += ` default="${f.d}"`;
    if (f.n) s += ` accepts=[${f.n.join(", ")}]`;
    if (f.min !== undefined || f.max !== undefined) s += ` range=[${f.min ?? ""}..${f.max ?? ""}]`;
    if (f.desc) s += ` - ${f.desc.length > 220 ? f.desc.slice(0, 217) + "..." : f.desc}`;
    lines.push(s);
  }
  return lines.join("\n");
}

/** Search node names and appinfo for a keyword. */
export function searchNodes(query: string, limit = 12): { name: string; info?: string; component?: string }[] {
  const q = query.toLowerCase();
  const scored: { name: string; score: number; info?: string; component?: string }[] = [];
  for (const [name, def] of Object.entries(uom.nodes)) {
    let score = 0;
    const lname = name.toLowerCase();
    if (lname === q) score += 100;
    else if (lname.startsWith(q)) score += 50;
    else if (lname.includes(q)) score += 30;
    if (def.info?.toLowerCase().includes(q)) score += 10;
    if (def.component?.toLowerCase() === q) score += 20;
    if (score > 0) scored.push({ name, score, info: def.info, component: def.component });
  }
  scored.sort((a, b) => b.score - a.score || a.name.localeCompare(b.name));
  return scored.slice(0, limit).map(({ name, info, component }) => ({ name, info, component }));
}
